---
title: "Assignment 1: Introduction"
author: "Sriya Gottumukkula"
output: pdf_document
---

## OVERVIEW

This exercise accompanies the introductory material in Environmental Data Analytics. 

## Directions
1.  Rename this file `<FirstLast>_A01_Introduction.Rmd` (replacing `<FirstLast>` with your first and last name).
2.  Change "Student Name" on line 3 (above) with your name.
3.  Work through the steps, **creating code and output** that fulfill each instruction.
4.  Be sure to **answer the questions** in this assignment document.
5.  When you have completed the assignment, **Knit** the text and code into a single PDF file.
6.  After Knitting, submit the completed exercise (PDF file) to the appropriate assignment section on Canvas.


## 1) Discussion Questions
Enter answers to the questions just below the >Answer: prompt.

1. What are your previous experiences with data analytics, R, and Git? Include both formal and informal training. 

> Answer: I worked with intermediate data analysis and visualization on excel but do not have any experince with R or Git hub

2. Are there any components of the course about which you feel confident?

> Answer: Since this is a first R course i am taking, I am new to most of the concepts 

3. Are there any components of the course about which you feel apprehensive?

> Answer: Although i am very interested to learn R and hopefully apply data analystics to inform environmental descsion making, i am a bit amprehensive about how much time it will take me be adept with all the skills i will be learning in this class 


## 2) GitHub

Provide a link below to your forked course repository in GitHub. Make sure you have pulled all recent changes from the course repository and that you have updated your course README file, committed those changes, and pushed them to your GitHub account. 

> Answer: https://github.com/sg717/EDA_Spring2025.git

## 3) Knitting
When you have completed this document, click the `knit` button.
